### ISSUE TITLE
Add a parameter to specialize the team against certain Pokemon/Types

### ISSUE THREAD

**Issue by Tetraden** [Swepps/pokemonautoteambuilder#26]
I'm just in the situation, that I have to get the Cascade Badge and I'm failing over and over.
Sadly, the generated teams are not of any use in this regard, so I'll have to create a team manually, wich is quite tideous of course, that's why the generator exists.
Is it possible to add an option for specializing the team against a certain type of pokemon?

**Comment by Swepps** [comment]
It isn't currently possible but that sounds like a great suggestion. I'll have a look into it :)

**Comment by Swepps** [comment]
I figured this was a pretty important feature so I spent some time today implementing it.

On the Autobuilder dialog there is now a toggle for each type that you can use to disable types you don't care about during generation.

In your example you can disable all types except water to come up with a team that should be good for getting the Cascade Badge. :)
